### ISSUE TITLE
Implementation compare_puzzels()

### ISSUE THREAD

**Issue by domien96** [GrigoriLomonosov/BinaryPuzzleSolver#1]
I don't see the point of printing both puzzels when they are not equal.
This implies two tasks for 1 function and
Not every caller wants this printing-behaviour. If a caller would need it, he can use code like this.

```
if not compare_puzzles(BinaryPuzzle* puzzle_1, BinaryPuzzle* puzzle_2) {
    print both puzzels;
}
```

**Comment by GrigoriLomonosov** [comment]
Kad da er snel ingeschreven voor het testen, anders moest ik in iedere test een if statement maken gelijk ier onder en da was gwn meer typwerk en tijdens het testen ben ik toch ma geïnteresseerd in de resultaten die ni lukken.

Sent from Outlookhttp://aka.ms/weboutlook

**Comment by domien96** [comment]
OK vergeet het dan niet weg te halen.
