### ISSUE TITLE
Find pairs

### ISSUE THREAD

**Issue by domien96** [GrigoriLomonosov/BinaryPuzzleSolver#2]
Is deze af? Deze klopt niet, deze checkt alleen van links naar rechts.
Bv. 00- zal  hij niet vinden.

**Comment by GrigoriLomonosov** [comment]
Idd, ma heeft niet met de richting te maken volgens mij. Is eerder omdat hij controleer of de vakjes aan beide kanten leeg zijn, maar dit is dus duidelijk niet altijd nodig. Kga er dan e ke vo kijken en aanpassen en testgevalletje toevoegen.

**Comment by GrigoriLomonosov** [comment]
Opgelost en testgevallen toegevoegd voor 4 hoeken, zowel col als row
