### ISSUE TITLE
Find pairs optimization

### ISSUE THREAD

**Issue by domien96** [GrigoriLomonosov/BinaryPuzzleSolver#3]
Volgende algoritme is volgens mij leesbaarder:
1 Rij per rij doorlopen
2 Hou de 2 vorige vakjes bij, als ze hetzelfde zijn en het huidige is leeg (in plaats van kijken of het vorige leeg is zoals het nu is.
3 indien huidige leeg is (puzzle->squares[i][j] == -1) pas je aan.

**Comment by GrigoriLomonosov** [comment]
Als je het zo doet gaat hij volgens mij '----00' niet vinden. In de aanpassing kijkt hij naar het vakje en het vorige. Als ze gelijk zijn, kijkt hij daarna naar de randen. Dit werkt ook voor alle hoeken dan.

**Comment by domien96** [comment]
Met uitzondering voor de randen, zou het dan niet lukken?

**Comment by GrigoriLomonosov** [comment]
Neen. Dit zal ook niet werken volgens mij '---00-' Er zal enkel een 1 komen op het laatste vakje. Het zal voorwaarts niet werken. Vind je de aanpassing niet leesbaar, kvind da nog meevallen eigenlijk en hij houdt ook rekening met de hoeken zo.

**Comment by domien96** [comment]
jawel , want mijn algoritme werkt langs 2 kanten he

**Comment by GrigoriLomonosov** [comment]
Dan ga je in beide richtingen overlopen of snap ik het niet? Das toch dubbel werk tan.

**Comment by domien96** [comment]
Als ge een koppel vindt, pas je beide kanten aan.

**Comment by GrigoriLomonosov** [comment]
Das toch wadak oorspronkelijk deed.

**Comment by domien96** [comment]
ongeveer, alleen zijn de indexen anders.
