### ISSUE TITLE
Refactoren methodes

### ISSUE THREAD

**Issue by GrigoriLomonosov** [GrigoriLomonosov/BinaryPuzzleSolver#5]
complete_RC en complete_pattern_RC bevatten redelijk wat analoge code om de kolommen te controleren/veranderen. Kan dit niet aangepast zodat hetzelfde wordt gedaan zonder dat de complexiteit omhoog gaat en er meer geheugen wordt gebruikt. 
Hetzelfde voor is_one_possible en is_zero_possible. Kan dit niet door een waarde (1,0) mee te geven aan een algemene functie.

**Comment by domien96** [comment]
Geen idee, ik heb de functies niet geschreven.
